// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
public enum LayerNames
{
    Default = 0,
    TransparentFX = 1,
    Ignore_Raycast = 2,
    Water = 4,
    UI = 5,
    Lighting_Internal_Game = 6,
    Lighting_Internal_Scene = 7,
}
